In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6676, 2329, 5369, 9848],
 [6676, 2329, 5369, 9485],
 [6676, 1854, 5369, 8917],
 [458, 2687, 2208, 656, 1119],
 [458, 2687, 2208, 656, 2792],
 [134, 6676, 7177, 5369, 1324],
 [4369, 12, 6499, 656]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6676 2329 5369 9848]
 [   0    0    0    0 6676 2329 5369 9485]
 [   0    0    0    0 6676 1854 5369 8917]
 [   0    0    0  458 2687 2208  656 1119]
 [   0    0    0  458 2687 2208  656 2792]
 [   0    0    0  134 6676 7177 5369 1324]
 [   0    0    0    0 4369   12 6499  656]]


In [12]:
## feature representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

2025-08-21 17:12:10.218882: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2
2025-08-21 17:12:10.219126: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2025-08-21 17:12:10.219143: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2025-08-21 17:12:10.219793: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-08-21 17:12:10.220435: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

2025-08-21 17:12:28.381843: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 1s 679ms/step


array([[[ 0.01738981,  0.04131458, -0.02788698,  0.04074246,
         -0.00492132,  0.04782974,  0.03200266, -0.03470298,
          0.00499157,  0.03381634],
        [ 0.01738981,  0.04131458, -0.02788698,  0.04074246,
         -0.00492132,  0.04782974,  0.03200266, -0.03470298,
          0.00499157,  0.03381634],
        [ 0.01738981,  0.04131458, -0.02788698,  0.04074246,
         -0.00492132,  0.04782974,  0.03200266, -0.03470298,
          0.00499157,  0.03381634],
        [ 0.01738981,  0.04131458, -0.02788698,  0.04074246,
         -0.00492132,  0.04782974,  0.03200266, -0.03470298,
          0.00499157,  0.03381634],
        [-0.04607867,  0.03550384, -0.00580845,  0.02574906,
         -0.00163748, -0.00886593, -0.02364098, -0.0146559 ,
          0.0452171 ,  0.01579502],
        [-0.02257509, -0.00791417,  0.03014472,  0.02376947,
          0.00839561,  0.02824846, -0.04533987, -0.03907015,
          0.00978774, -0.03138673],
        [-0.01962826, -0.01469819, -0.01132607, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 6676, 2329, 5369, 9848], dtype=int32)

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 201ms/step


array([[ 0.01738981,  0.04131458, -0.02788698,  0.04074246, -0.00492132,
         0.04782974,  0.03200266, -0.03470298,  0.00499157,  0.03381634],
       [ 0.01738981,  0.04131458, -0.02788698,  0.04074246, -0.00492132,
         0.04782974,  0.03200266, -0.03470298,  0.00499157,  0.03381634],
       [ 0.01738981,  0.04131458, -0.02788698,  0.04074246, -0.00492132,
         0.04782974,  0.03200266, -0.03470298,  0.00499157,  0.03381634],
       [ 0.01738981,  0.04131458, -0.02788698,  0.04074246, -0.00492132,
         0.04782974,  0.03200266, -0.03470298,  0.00499157,  0.03381634],
       [-0.04607867,  0.03550384, -0.00580845,  0.02574906, -0.00163748,
        -0.00886593, -0.02364098, -0.0146559 ,  0.0452171 ,  0.01579502],
       [-0.02257509, -0.00791417,  0.03014472,  0.02376947,  0.00839561,
         0.02824846, -0.04533987, -0.03907015,  0.00978774, -0.03138673],
       [-0.01962826, -0.01469819, -0.01132607, -0.04940757, -0.00558943,
         0.04720097,  0.04982181,  0.0355666 